const productsId = {
    64: "Caciocavallo",
    86: "Scamorza",
    80: "Ricotta Salata",
    84: "Fior di ricotta",
    85: "Bocconcini di latte di bufala",
    107: "Provolone del Cilento",
    108: "Mozzarella di bufala",
    112: "Caciocavallo aromatizzato al peperoncino",
    114: "Bufala con cuore in olio d'oliva",
    119: "Cacioricotta di capra",
    130: "Fiordilatte",
    170: "Mozzarella nella mortella",
    187: "Caciocavallo affinato nelle vinacce di Aglianico",
    14: "Scamorza affumicata",
    15: "Provolone Cilento",
    16: "Bocconcino bufala",
    17: "Maxi mozzarella bufala",
    8: "Treccia",
    3: "Caciocavallo affumicato",
    4: "Caso re vacca",
    1: "mozzarella",
    2: "bufala",
}
export default productsId;